// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebarstutorials = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],


  tutorialsSidebar: [
    {
      type: 'category',
      label: '教程专栏',
      link: { 
        type: 'doc',
        id: 'intro' // 关联tutorials总说明
      },
      items: [
        {
          type: 'category',
          label: 'Linux基础', // 下一级分类1
          link: {
            type: 'doc',
            id: 'linux/intro'
          },
          items: [ ]
        }
      ]
    }
  ]
};

export default sidebarstutorials;
