// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebarsprojects = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],


  docSidebar: [
    {
      type: 'category',
      label: '项目札记',
      link: { 
        type: 'doc',
        id: 'project-notes/intro' // 关联project-notes总说明
      },
      items: [
        {
          type: 'category',
          label: 'STM32MP1', // 下一级分类1
          link: {
            type: 'doc',
            id: 'project-notes/stm32mp1/intro'
          },
          items: [
            'project-notes/stm32mp1/kernel/kernel-compile' // 下二级示例
          ]
        }
      ]
    },
    {
      type: 'category',
      label: '技术随笔',
      link: {
        type: 'doc',
        id: 'tech-notes/intro' // 关联tech-notes总说明
      },
      items: [
        {
          type: 'category',
          label: 'Linux基础', // 下一级分类1
          link: {
            type: 'doc',
            id: 'tech-notes/linux-basics/command-line'
          },
          items: [] // 预留扩展空间
        }
      ]
    },
    {
      type: 'category',
      label: '资源归档',
      link: {
        type: 'doc',
        id: 'resources/intro'
      },
      items: [],  // 预留扩展空间 
    }
  ]
};

export default sidebarsprojects;
